### PR TITLE
188 converter

### LINKED ISSUE #188: DB migration script
Internal format for some fields has changed from v1.0 to latest version. These changes have been carried out in order to provide multiple cardinality and localization. 

This is a list of the fields that should be reformatted:
- otherIdentifier
- theme
- temporal extension
- isVersionOf
- conformsTo
- contactPoint
- creator
- resource License
- ...

Once migration has been performed, also check for serialization for
- dct:identifier
- adms:identifier 
- dct:modified
- accrualPeriodicity
- dct:spatial
- dct:language
- ,,,

### PR DESCRIPTION
**Pull request by cezio**
fix #188 

How to use it:
 * run `vocabulary initdb` to update dcatapit schema
 * run `vocabulary migrate_data` to update dcatapit fields notation

Command `migrate_data` will:
 * fetch all datasets (including private datasets)
 * convert `creator`/`conforms_to`/`theme`/`temporal_coverage`/`alternate_identifier` fields to new storage
 * remove unused fields: `temporal_start`/`temporal_end`/`creator_name`/`creator_identifier`, empty `alternate_identifier`, `conforms_to` fields to avoid validation errors
 * munge tag `name` value to avoid validation error
 * remove `metadata_modified` field to force modification in database.

### CODE REVIEW

**Comment by cezio** [comment]
> isVersionOf

This field is url type, wasn't changed since initial add, and doesn't need migration.

> contactPoint (that refers to the Agents for which the format has been changed and so rights_holder, creator and publisher)

 contactPoint element in rdf is generated from organization connected to dataset. `holder_*` fields didn't change their format. See https://github.com/geosolutions-it/ckanext-dcatapit/issues/72

> resource License (the license for resource is mandatory so we need to assign at least the dataset license to their resources)

AFAIR, it's not mandatory. We have `ignore_missing` validator assigned. Besides, field didn't change since addition (and code works when there's no resource license). 

> Are there other fields that have been changed? Like geonames for example? (we need to be 100% sure)

geonames  field is url type, and is not changed since add. We did however change UI for that field, introduced helper field with location name (https://github.com/geosolutions-it/ckanext-dcatapit/issues/146). But this doesn't change data processing in any way.

I don't see any other field that would require data migration in dcatapit.

**Comment by giorgialodi** [comment]
Guys, I still follow you, at least when I can :) Just a few notes on the model. License for the distributions (resources): IT IS a mandatory metadata. Moreover, contactPoint is a property that links a Dataset to an Organization that is not declared as Agent and the properties associated with Organization are not the same as those associated with the Agent, at the moment

**Comment by tdipisa** [comment]
@cezio 

> This field is url type, wasn't changed since initial add, and doesn't need migration.

OK

>  contactPoint element in rdf is generated from organization connected to dataset. `holder_*` fields didn't change their format. See https://github.com/geosolutions-it/ckanext-dcatapit/issues/72

OK

>AFAIR, it's not mandatory. We have `ignore_missing` validator assigned. Besides, field didn't change since addition (and code works when there's no resource license).

Yes, we have 'ingore_missing' as validator just for backward compatibility and for harvesting purposes. The license assignement is internally managed by the code of the extension in order to be valorized in each case.

However, in the old version of the extension, the resource license was the same of the dataset. So what we have to do now within the migration script, is to assing the right license to resource using the one of the dataset. 

>geonames  field is url type, and is not changed since add. We did however change UI for that field, introduced helper field with location name (https://github.com/geosolutions-it/ckanext-dcatapit/issues/146). But this doesn't change data processing in any way.

OK

Did you already tested the RDF serialization, for both dataset.rdf and catalog.rdf, to check if it is correct and all agent are correclty filled?

We also need to update the README introducing a specific new section that explain the migration procedure.

**Comment by cezio** [comment]
> 40038ERROR: [doc=bd4de7196f840f5a03343eec85551323] multiple values encountered for non multiValued field dcat_theme: [GOVE, ENVI]400

This means solr schema wasn't updated properly. It should contain line: `<field name="dcat_theme" type="string" indexed="true" stored="false" multiValued="true"/>`

> File "/usr/lib/ckan/default/src/ckanext-dcatapit/ckanext/dcatapit/commands/dcatapit.py", line 394, in update_creator
for idx, ex in enumerate(pdata['extras']):
KeyError: 'extras'
(default)[ckan@bolzano ~]$

This should be fixed with 17d69cd.

**Comment by cezio** [comment]
> During the dataset migration the holder_name is set using the organization name, the localized
organization title should be used instead. I noticed that for harvested dataset (i.e. using the provbz
CSW harvester) the holder_name is the one retrieved from the metadata and not the organization name,
this is correct but why we have this difference?

I'm not sure what you're asking about here. In general, holder information is meant to be sourced from organization. Harvesters can update organization data as long as they have consistent identifiers. In other cases we just source holder information with organization's data when possible. Migration doesn't do anything specific for this information, it just uses plugin's logic here.

**Comment by cezio** [comment]
> if the IPA code is missing during the migration, a temporary code must be used (i.e. 'tmp_ipa_code') and the migration report log file updated accordingly so the admin can see it and review temporary changes performed during the migration

Should this temp ipa code be hardcoded value or configurable?

**Comment by tdipisa** [comment]
@cezio 

1) I noticed that after the migration the organization name is assigned to the holder name in dataset read page (i. e. regione-autonoma-trentino-alto-adige) but the organization localized title should be used (i. e. Regione Autonoma Trentino - Alto Adige)

2) We have to use **tmp_ipa_code** and log the related info in migration report as I specified to allow the admin to manually review IPAs

**Comment by tdipisa** [comment]
@cezio see below please:

- [ ] Logs like the following mean that all field are correctly migrated except for the Temporal Coverage that will be empty in the migrated dataset, right?

`dataset agricoltura-e-foreste-manodopera-aziendale: cannot use temporal coverage (u'2015', u'2025'): 'Invalid date input: 2025' updating agricoltura-e-foreste-manodopera-aziendale`

- [ ] There's a wrong behavior in holder_name management:

take into account at the following cases:

1.  when a new dataset is created the rights holder is the owner organization selected for the dataset. More holder_name record in package_multilang must be created for each locales in group_multilang for the that organization. In this way we will have the rights holder properly translated when the language is changed.

2.  during the migration, the holder_name of existing datasets must be valorized with the dataset's organization title and we need an holder_name record in package_multilang for each organizaton title translations in group_multilang.In this way we will have the rights holder properly translated when the language is changed.

3.  when an organizaton title is modified for a specific language the related holder_name in package_multilang table must be updated accordingly, otherwise we will not have the field correclty translated if we change language in ckan GUI.

- [ ] The modified date field is mandatory but it is not currently fixed during the migration if old values are not valid or missing. In those cases a default value must be used with the current date and the information logged into the migration report log file.

see for exampe dataset: http://192.168.1.121/dataset/trasporto-pubblico-locale

- [ ] I see now that after the migration the dataset identifier value is lost (this is a mandatory field !)

- [ ] If the frequency of update is missing or wrong in old datasets the default value (frequency: UNKNOWN) must be used during the migration and this information logged into the migration report log file.

- [ ] We have a problem with the 'conforms to' field. After the migration I can see it in dataset read page (but only the std subfield) but in dataset edit section the field is empty. 

See for example teh following dataset after th emigration: http://192.168.1.121/dataset/piani-urbanistici-elementi-lineari

- [ ] In RDF output of some dataset for example http://192.168.1.121/dataset/elenco-prezzi-opere-edili-2016.rdf we have a wrong rightsholder:

    <dct:rightsHolder>
      <foaf:Agent rdf:nodeID="N7847869b5ae14ddb862286a45015c9c0">
        <foaf:name xml:lang="de">Autonome Provinz Bozen. Agentur öffentliche Verträge</foaf:name>
        **<foaf:name xml:lang="it">Provincia Autonoma di Bolzano: Agenzia Contratti Pubblici</foaf:name>
        <foaf:name xml:lang="it">APB: Agentur  öffentliche Verträge</foaf:name>**
        <rdf:type rdf:resource="http://dati.gov.it/onto/dcatapit#Agent"/>
        <foaf:name xml:lang="en">APB: Agentur  öffentliche Verträge</foaf:name>
        <dct:identifier>tmp_ipa_code_22</dct:identifier>
      </foaf:Agent>

**Comment by tdipisa** [comment]
> However, those should be reviewed, because we can have a situation, when start and end are at the same moment,

From specs the temporal coverage is not mandatory but if provided only the temporal_start is mandatory, so in these case we have to maintain only the temporal_start.

**Comment by cezio** [comment]
> From specs the temporal coverage is not mandatory but if provided only the temporal_start is mandatory, so in these case we have to maintain only the temporal_start.

This is preserved. What i'm referring is that old temporal coverage values were set with a bit of seldom, providing, for example, only year.

**Comment by cezio** [comment]
> I see now that after the migration the dataset identifier value is lost (this is a mandatory field !)

Could you verify that? There can be datasets with empty `identifier` (or missing one). They will have identifier generated with uuid. Existing identifiers should be preserved.

**Comment by tdipisa** [comment]
@cezio 
I already verified that (please use the DB dump I shared with you). I checked for example the dataset 
http://192.168.1.121/dataset/piani-urbanistici-elementi-lineari
and after the migration the identifier is gone.

**Comment by cezio** [comment]
> @cezio
I already verified that (please use the DB dump I shared with you). I checked for example the dataset
http://192.168.1.121/dataset/piani-urbanistici-elementi-lineari
and after the migration the identifier is gone.

 I tried migration with clean db dump and identifier (`p_bz:f890fa1c-1a7b-41cd-a498-ab8eb85a9385`) is preserved.

**Comment by cezio** [comment]
>  We have a problem with the 'conforms to' field. After the migration I can see it in dataset read page (but only the std subfield) but in dataset edit section the field is empty.

Old data contain only string identifier, which is used as standard's name in new data format. However, I can't reproduce. I see standard in read and edit view:

image

image

**Comment by cezio** [comment]
>  If the frequency of update is missing or wrong in old datasets the default value (frequency: UNKNOWN) must be used during the migration and this information logged into the migration report log file.

frequency was handled but wasn't reported. This should be visible in logs now.

**Comment by cezio** [comment]
> In RDF output of some datasets for example http://192.168.1.121/dataset/elenco-prezzi-opere-edili-2016.rdf we have a wrong rightsholder:

Could you verify if this still happens? i got correct rightsHolder data:
```
    <dct:rightsHolder>
      <foaf:Agent rdf:nodeID="Ne804755f067a4b46b4cae6ab19274873">
        <foaf:name xml:lang="it">Provincia Autonoma di Bolzano: Agenzia Contratti Pubblici</foaf:name>
        <foaf:name xml:lang="de">Autonome Provinz Bozen. Agentur öffentliche Verträge</foaf:name>
        <dct:identifier>tmp_ipa_code_22</dct:identifier>
        <foaf:name xml:lang="en">APB: Agentur  öffentliche Verträge</foaf:name>
        <rdf:type rdf:resource="http://dati.gov.it/onto/dcatapit#Agent"/>
      </foaf:Agent>
    </dct:rightsHolder>
```

**Comment by tdipisa** [comment]
- [ ] During the migration I found some things to review again:

for example, considering the following:

> dataset elenco-fermate-mezzi-sasa has the same temporal coverage start/end: 2015/2015, using start only
> dataset Verzeichnis der Haltestellen von SASA-Fahrzeugen: no identifier. generating new one
> dataset Verzeichnis der Haltestellen von SASA-Fahrzeugen: invalid modified date None. Using now timestamp
> updating 2c1be0e6-37c4-4c71-8006-9f2147bbfac7 elenco-fermate-mezzi-sasa

> dataset elenco-fermate-mezzi-sasa has the same temporal coverage start/end: 2015/2015, using start only

we have 	From: 2015-01-01 to: 2015-01-01
this does not make sense, we can have only **From: 2015-01-01**

> dataset Verzeichnis der Haltestellen von SASA-Fahrzeugen: no identifier. generating new one

use the dataset name not the dataset title in the log

> dataset Verzeichnis der Haltestellen von SASA-Fahrzeugen: invalid modified date None. Using now timestamp

use the dataset name not the dataset title in the log

and we have a wrong value 2018-08-07' (same issue in all datasets)

> updating 2c1be0e6-37c4-4c71-8006-9f2147bbfac7 elenco-fermate-mezzi-sasa

- [ ] The **conforms_to** issue described above still persists

- [ ] In RDF output  for example http://192.168.1.121/dataset/elenco-prezzi-opere-edili-2016.rdf we have a wrong rightsholder now I have the following:

    <dct:rightsHolder>
      <dcatapit:Agent rdf:nodeID="N38b8c315cc18454db3703c597d09ea9a">
        <rdf:type rdf:resource="http://xmlns.com/foaf/0.1/Agent"/>
        <foaf:name xml:lang="de">Autonome Provinz Bozen. Agentur öffentliche Verträge</foaf:name>
        **<foaf:name xml:lang="it">Provincia Autonoma di Bolzano: Agenzia Contratti Pubblici</foaf:name>
        <dct:identifier>tmp_ipa_code_22</dct:identifier>
        <foaf:name xml:lang="it">APB: Agentur  öffentliche Verträge</foaf:name>**
      </dcatapit:Agent>
    </dct:rightsHolder>

**Comment by cezio** [comment]
>> dataset elenco-fermate-mezzi-sasa has the same temporal coverage start/end: 2015/2015, using start only
> we have From: 2015-01-01 to: 2015-01-01
> this does not make sense, we can have only From: 2015-01-01

 Right. temporal coverage was created before that validation. Now values should be only for 'from' field.

> use the dataset name not the dataset title in the log

Wouldn't title be more helpful to get to dataset? it's a part of url usually.

> and we have a wrong value 2018-08-07' (same issue in all datasets)

 Fixed

> In RDF output for example http://192.168.1.121/dataset/elenco-prezzi-opere-edili-2016.rdf we have a wrong rightsholder no

 Should be fixed also. There was a duplicated logic that would populate foaf:name elements in rights holder (it would insert name with default language - which may be different from current lang from web process, and second time by inserting names from localized values).

**Comment by tdipisa** [comment]
@cezio 

> Wouldn't title be more helpful to get to dataset? it's a part of url usually.

- [ ] yes but is the **name** that is part of the URL not the dataset **title**.  In report log file we have to use dataset name and not the localized dataset title. In the example I mentioned the name of the dataset is **elenco-fermate-mezzi-sasa**

> Should be fixed also. There was a duplicated logic that would populate foaf:name elements in rights holder (it would insert name with default language - which may be different from current lang from web process, and second time by inserting names from localized values). 

- [ ] in RDF now I have IT foas:name with the text in DE even if the owner org has the IT translations:

```
    <dct:rightsHolder>
      <foaf:Agent rdf:nodeID="N009bffb1660a4feb9fa1802977458d87">
        <foaf:name xml:lang="en">APB: Agentur  öffentliche Verträge</foaf:name>
        **<foaf:name xml:lang="it">APB: Agentur  öffentliche Verträge</foaf:name>**
        <rdf:type rdf:resource="http://dati.gov.it/onto/dcatapit#Agent"/>
        <dct:identifier>tmp_ipa_code_22</dct:identifier>
        <foaf:name xml:lang="de">Autonome Provinz Bozen. Agentur öffentliche Verträge</foaf:name>
      </foaf:Agent>
    </dct:rightsHolder>
```

If you see at the owner org translations:

- the title in IT is **PAB: Agenzia Contratti Pubblici**
- the title in DE is **APB: Agentur  öffentliche Verträge**

- [ ] The **holder_name** management is not complete, it seems that only the point 3 above has ben implemented. Currently the holder_name is not properly translated in dataset read page and RDF rightHolder output. As I mentioned:

> in dataset read page use the dataset ID to check if it is harvested or local. If harvested use teh existing holder info in package_dict. **If local, retrieve the localized title from the owner organization and the related IPA code. Use then this localized title to visualize the holder_name**

obviously also the ORG IPA code should be shown instead of the one we have in holder_identifier (the same for RDF output)

- [ ] In dataset read page we have different date format for modified date and temporal extent. Please use for both the one we are using now for the modified date (that is gg-mm-yyyy)

- [ ] Please consider the fragment of report log below:

```
---------
dataset misure-meteo-e-idrografiche: cannot use temporal coverage (u'01/01/2015', u'heute'): u'Invalid date input: heute'
dataset Messdaten Meteo: no identifier. generating new one
dataset Messdaten Meteo: invalid modified date None. Using now timestamp
updating 1512fa49-3e97-40d7-9bdb-2fc76c9efe3c misure-meteo-e-idrografiche
---------
```

In that case the temporal start can be maybe preserved, no?

**Comment by cezio** [comment]
> It seems that during the migration each existing Tag translations is lost for a dataset:

yes, because translated tags don't pass tag validation, so i had to munge them when saving.

**Comment by cezio** [comment]
> in RDF now I have IT foas:name with the text in DE even if the owner org has the IT translations:
    <dct:rightsHolder>
      <foaf:Agent rdf:nodeID="N009bffb1660a4feb9fa1802977458d87">
        <foaf:name xml:lang="en">APB: Agentur  öffentliche Verträge</foaf:name>
        **<foaf:name xml:lang="it">APB: Agentur  öffentliche Verträge</foaf:name>**
        <rdf:type rdf:resource="http://dati.gov.it/onto/dcatapit#Agent"/>
        <dct:identifier>tmp_ipa_code_22</dct:identifier>
        <foaf:name xml:lang="de">Autonome Provinz Bozen. Agentur öffentliche Verträge</foaf:name>
      </foaf:Agent>
    </dct:rightsHolder>
> If you see at the owner org translations:
> the title in IT is PAB: Agenzia Contratti Pubblici
> the title in DE is APB: Agentur öffentliche Verträge

I've investigated this, and this is remote package, so we have holder information in package itself. In this case, we have full translation in multilang but also original name from harvesting baked into package data, which doesn't have language assigned. I've added all values to rightsHolder:

```
    <dct:rightsHolder>
      <foaf:Agent rdf:nodeID="N05830e746b144c768b25cb6c0ed843a8">
        <foaf:name>APB: Agentur  öffentliche Verträge</foaf:name>
        <foaf:name xml:lang="it">Provincia Autonoma di Bolzano: Agenzia Contratti Pubblici</foaf:name>
        <foaf:name xml:lang="en">APB: Agentur  öffentliche Verträge</foaf:name>
        <rdf:type rdf:resource="http://dati.gov.it/onto/dcatapit#Agent"/>
        <foaf:name xml:lang="de">Autonome Provinz Bozen. Agentur öffentliche Verträge</foaf:name>
        <dct:identifier>tmp_ipa_code_9</dct:identifier>
      </foaf:Agent>
    </dct:rightsHolder>
```

As for holder_identifier, it was taken from organization, because package didn't have any. I've updated converter and missing holder_identifier will be generated to temp one.

**Comment by cezio** [comment]
> As for holder_identifier, it was taken from organization, because package didn't have any. I've updated converter and missing holder_identifier will be generated to temp one.

There was also additional case of rights_holder in edit form. According to logic currently implemented, rights holder info is read-only in form, and is populated from organization data. This included also cases when holder info was present in dataset. I've added `dataset_is_local` flag so we can distinct situation when dataset should have holder info preserved, and not overriden from organization.

**Comment by tdipisa** [comment]
> yes, because translated tags don't pass tag validation, so i had to munge them when saving.

And why you don't notified that and you have arbitrarily decided to remove them? These must be preserved, what are possible solutions?

> I've investigated this, and this is remote package, so we have holder information in package itself. In this case, we have full translation in multilang but also original name from harvesting baked into package data, which doesn't have language assigned. I've added all values to rightsHolder:

The sample package I used (**elenco-prezzi-opere-edili-2016**) is not a remote package (I've checked this in harvest_object table). In that case we have decided to use translated values from owner org, if multilang is enabled obviously, or direclty the standard org title (if multilang is not enabled).

> There was also additional case of rights_holder in edit form. According to logic currently implemented, rights holder info is read-only in form, and is populated from organization data. This included also cases when holder info was present in dataset. I've added dataset_is_local flag so we can distinct situation when dataset should have holder info preserved, and not overriden from organization.

I did not mention changes to the edit section for this. In any case the modification you have suggested  can makes sense but existing holder_name/holder_identifier values in package_dict must be preserved.

**Comment by cezio** [comment]
> And why you don't notified that and you have arbitrarily decided to remove them? These must be preserved, what are possible solutions?

I've notified you on chat, but didn't get any response how to handle this. Also, there's comment above code block with information why this hack: https://github.com/geosolutions-it/ckanext-dcatapit/pull/213/files#diff-b5bcebaf0f8af1537856173cdf14a9c3R400

Let me know if you have better solution for this problem.

> The sample package I used (elenco-prezzi-opere-edili-2016) is not a remote package (I've checked this in harvest_object table). In that case we have decided to use translated values from owner org, if multilang is enabled obviously, or direclty the standard org title (if multilang is not enabled).

**Pull request merged**
